name: golangci-lint

on:
  push:
  pull_request:

jobs:
  golangci:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.23"

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.64.7
